### ISSUE TITLE
Feature request: `str_pad()` and `str_split()`

### ISSUE THREAD

**Issue by elipousson** [rossellhayes/stringstatic#1]
Would you be interested in seeing more base R equivalents for stringr functions for the package? I'd love to add `str_pad()` and `str_split()` if you're up for contributions. I could also generalize this issue to include a checklist of `{stringr}` functions that could be added.

**Comment by rossellhayes** [comment]
@elipousson I'd be happy for you to contribute any functions that you'd find useful! I've been slowly adding functions as I've needed them for my own projects, so I'd be happy for you to do the same!

One thing to note: because these functions are intended to be incorporated directly into other authors' code, the package is released into the public domain with a CC0 license. I would of course credit your contributions in `stringstatic`, but there's no guarantee that your code would be credited when integrated into other packages. I just want to make sure you'd be comfortable releasing your work in this way.

**Comment by elipousson** [comment]
I've got a version of [`str_pad()`](https://github.com/elipousson/stringstatic/blob/main/inst/staticexports/str_pad.R) that works (I think):

```
str_pad <- function(string, width, side = c("left", "right", "both"), pad = " ") {
  stopifnot(
    is.numeric(width),
    width > 0,
    nchar(pad) == 1
  )

  side <- match.arg(side)

  rep_pad <- function(width) {
    vapply(
      width,
      function(x) {
        paste0(rep.int(pad, max(x, 0)), collapse = "")
      },
      ""
    )
  }

  pad_side <- width - nchar(string)
  pad_front <- pad_side %/% 2

  switch(side,
    "left" = paste0(rep_pad(pad_side), string),
    "right" = paste0(string, rep_pad(pad_side)),
    "both" = paste0(rep_pad(pad_front), string, rep_pad(pad_side - pad_front))
  )
}
```

My version of [`str_split()`](https://github.com/elipousson/stringstatic/blob/main/inst/staticexports/str_split.R) and `str_split_fixed()` is incomplete. It has been a few weeks since I looked at it but I wasn't able to get the `simplify = TRUE` parameter working. Suggestions are welcome!

**Comment by elipousson** [comment]
Whoops. Seeing this again this morning, I'm realizing that I assumed a length 1 pad - not a vector which `stringr::str_pad()` definitely supports. Still happy for suggestions but I can just make a second attempt in the next couple weeks.

**Comment by rossellhayes** [comment]
@elipousson Thank you for sharing this! I opened a PR which includes a version of `str_pad()` I adapted from your code. Luckily, it wasn't too big of a lift to get `str_pad()` vectorized.

The other changes were mostly just to ensure this function handles edge cases as close as possible to `stringr`'s implementation.

I also added a `use_width` argument, which was added in the current dev version of `stringr` (it's mostly used for things like Unicode diacritics where you can have two characters that only occupy one space of width).

I'll take a look at `str_split()` in the next couple of days. Getting `simplify` arguments to work correctly is always tricky for me!

**Comment by elipousson** [comment]
Awesome. Your pull request looks great but I'll test it out and let you know if I spot any issues. It is always so educational to contribute to your projects - I didn't even know strrep existed and using a combo of floor() and ceiling() is much easier to understand than the approach using integer division.

**Comment by rossellhayes** [comment]
The `str_pad()` PR (#4) is now merged, and I've just opened a PR for `str_split()` (#7). I'd love to hear your thoughts on that one as well. Thanks for your help in getting these functions together, it's always fun working with you and it's an awesome addition to the package!

**Comment by elipousson** [comment]
Apologies for never getting back to you on the review request! Really appreciate you bringing these updates forward into the package. I've been using stringstatic a fair amount and hoping to create a more limited version of [`{toanycase}`](https://github.com/Tazinho/snakecase) that only uses the static functions instead of stringr.

**Comment by rossellhayes** [comment]
@elipousson That sounds awesome! Please feel free to submit feature requests or PRs if you find any functionality that isn't covered here yet
